package DAL;
// Generated Jan 20, 2015 1:11:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer id;
     private Spel spel;
     private String comment;
     private String username;
     private Date datum;
     private int reactieVerwijderen;

    public Comment() {
    }

	
    public Comment(Spel spel, String comment, String username, int reactieVerwijderen) {
        this.spel = spel;
        this.comment = comment;
        this.username = username;
        this.reactieVerwijderen = reactieVerwijderen;
    }
    public Comment(Spel spel, String comment, String username, Date datum, int reactieVerwijderen) {
       this.spel = spel;
       this.comment = comment;
       this.username = username;
       this.datum = datum;
       this.reactieVerwijderen = reactieVerwijderen;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Spel getSpel() {
        return this.spel;
    }
    
    public void setSpel(Spel spel) {
        this.spel = spel;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public int getReactieVerwijderen() {
        return this.reactieVerwijderen;
    }
    
    public void setReactieVerwijderen(int reactieVerwijderen) {
        this.reactieVerwijderen = reactieVerwijderen;
    }




}


